### ISSUE TITLE
Invalid Sequence Error 

### ISSUE THREAD

**Issue by touhonoob** [binance-chain/go-sdk#45]
Got the following error when trying to send multiple orders simultaneously 

```
bad response, status code 403, response: {\"code\":403,\"failed_tx_index\":0,\"message\":\"Invalid sequence. Got 40, expected 41\",\"success_tx_results\":[]}\n"
```

**Comment by guagualvcha** [comment]
Hi, send the transaction of the same address simultaneously will indeed cause `Invalid sequence` error.
To defend the replay attack, the sequence of an address should increase in order. But if send transaction too fast(use async/sync) or simultaneously, the previous transaction haven't included in block yet, go-sdk will fetch the current sequence and sign new transaction, cause sequence discontinuous.
Because there is no  guarantee the previous transaction will be included in block, so we get account sequence each time before send the transaction instead of increase it automatically.

**Comment by touhonoob** [comment]
@guagualvcha Is it possible to allow users to assign sequence number for each transaction manually? For applications like market making bot it's fatal to send both bid & ask orders at the same time.

**Comment by guagualvcha** [comment]
make sense. I will submit a PR soon.

**Comment by guagualvcha** [comment]
@touhonoob  hi, go-sdk have updated to support custom sequence.
example:
```
acc,err:=client.GetAccount(client.GetKeyManager().GetAddr().String())
_, err = client.CreateOrder(tradeSymbol, nativeSymbol, msg.OrderSide.BUY, 100000000, 100000000, true, transaction.WithAcNumAndSequence(acc.Number,acc.Sequence))
_, err = client.CreateOrder(tradeSymbol, nativeSymbol, msg.OrderSide.BUY, 100000000, 100000000, true, transaction.WithAcNumAndSequence(acc.Number,acc.Sequence+1))
_, err = client.CreateOrder(tradeSymbol, nativeSymbol, msg.OrderSide.BUY, 100000000, 100000000, true, transaction.WithAcNumAndSequence(acc.Number,acc.Sequence+2))
```
